export const C = {
  bg: "#FFF8F0",
  card: "#FFFFFF",
  primary: "#FF5722",
  secondary: "#2979FF",
  accent: "#FFC107",
  teal: "#00BCD4",
  success: "#43A047",
  danger: "#E53935",
  muted: "#90A4AE",
  dark: "#1A237E",
  mid: "#546E7A",
  light: "#E3F2FD",
  cream: "#FFF3E0",
};

export const FF = {
  display: "'Chewy', 'Noto Sans KR', cursive",
  body: "'Nunito', 'Noto Sans KR', sans-serif",
};

export const css = {
  app: {
    fontFamily: FF.body,
    minHeight: "100vh",
    background: C.bg,
    color: C.dark,
  },
  header: (bg) => ({
    background: bg || C.primary,
    padding: "14px 20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  }),
  htitle: { color: "#fff", fontSize: 19, fontWeight: 900, margin: 0, fontFamily: FF.display, letterSpacing: 0.5 },
  wrap: { maxWidth: 640, margin: "0 auto", padding: "24px 16px" },
  card: (extra) => ({
    background: C.card,
    borderRadius: 20,
    padding: 20,
    marginBottom: 12,
    boxShadow: "0 2px 12px rgba(26,35,126,0.08)",
    ...extra,
  }),
  btn: (bg, color = "#fff", extra) => ({
    background: bg,
    color,
    border: "none",
    borderRadius: 50,
    padding: "11px 22px",
    fontWeight: 800,
    fontSize: 14,
    cursor: "pointer",
    fontFamily: FF.body,
    ...extra,
  }),
  pill: (bg, color = "#fff") => ({
    background: bg,
    color,
    borderRadius: 50,
    padding: "4px 13px",
    fontSize: 12,
    fontWeight: 800,
    display: "inline-block",
  }),
  tab: (active, color) => ({
    background: active ? color || C.primary : C.card,
    color: active ? "#fff" : C.mid,
    border: active ? "none" : `2px solid ${C.light}`,
    borderRadius: 50,
    padding: "9px 17px",
    fontWeight: 800,
    fontSize: 13,
    cursor: "pointer",
    fontFamily: FF.body,
    transition: "all 0.15s",
  }),
  input: {
    border: "2.5px solid #CFD8DC",
    borderRadius: 14,
    padding: "12px 16px",
    fontSize: 15,
    fontFamily: FF.body,
    outline: "none",
    background: "#FFFFFF",
    width: "100%",
    boxSizing: "border-box",
    color: C.dark,
  },
  toast: (type) => ({
    position: "fixed",
    top: 20,
    left: "50%",
    transform: "translateX(-50%)",
    background: type === "err" ? C.danger : C.success,
    color: "#fff",
    padding: "13px 28px",
    borderRadius: 50,
    fontWeight: 800,
    zIndex: 9999,
    boxShadow: "0 6px 24px rgba(0,0,0,0.18)",
    fontSize: 15,
    whiteSpace: "nowrap",
  }),
};
